<div class="animation_box d-none d-lg-block">
    <span class="animation_box-item bg-style"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item bg-style"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item bg-style"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item bg-style"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item bg-style"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item bg-style"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item bg-style"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item bg-style"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
    <span class="animation_box-item"></span>
</div>